### ISSUE TITLE
Remove navigation bar and build the fonctionality inside the left hand menu

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-mail-settings#145]
Whenever a settings page is accessed, the sections will display the children of that page and user can click on each child to jump to the underlying section on the page. The highlight of children should follow the scoll of users (unlike what is being done by google calendar)

Note: we may want to consider doing this in ProtonVPN first

**Comment by EpokK** [comment]
@matstaz could you share a design for this issue please?

**Comment by matstaz** [comment]
@EpokK designs are being done by Stelian. Will get something back for us to review pretty soon.

**Comment by matej-n** [comment]
Hey, not sure about the status of this, but i just wanted to mention that currently, the highlight in the navigation menu is incorrect. You just need to scroll up and down for a few seconds and you should be able to reproduce it. Ex: Invoices is highlighted instead of Plans.

Here is a video: https://recordit.co/Yxyy205afF

Used: Chrome on Windows 10.

**Comment by EpokK** [comment]
Duplicated https://github.com/ProtonMail/proton-mail-settings/issues/171
